basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from basic_app.views import SignUpView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'basic_app'
urlpatterns = [
    url(r'^$', views.index.as_view(),name = 'index'),
    url(r'createp/',views.createp.as_view(),name ='createp'),
    url(r'patient_list/$',views.listp.as_view(),name = 'patient_list'),
    url(r'updatep/(?P<pk>\d+)/$',views.updatep.as_view(),name = 'updatep'),
    url(r'updateh/(?P<pk>\d+)/$',views.updateh.as_view(),name = 'updateh'),
    url(r'updated/(?P<pk>\d+)/$',views.updated.as_view(),name = 'updated'),
    url(r'details/(?P<pk>\d+)/$',views.details.as_view(),name ='details'),
    url(r'createh/',views.createh.as_view(),name ='createh'),
    url(r'hospital_details/(?P<pk>\d+)/$',views.hospital_details.as_view(),name ='hospital_details'),
    url(r'hospital_list/$',views.listh.as_view(),name = 'hospital_list'),
    url(r'patient_list/(?P<pk>\d+)/$',views.details.as_view(),name = 'patient_list'),
    url(r'hospital_list/(?P<pk>\d+)/$',views.hospital_details.as_view(),name = 'hospital_list'),
    url(r'patient_confirm_delete/(?P<pk>\d+)/$',views.deletep.as_view(),name = 'patient_confirm_delete'),
    url(r'hospital_confirm_delete/(?P<pk>\d+)/$',views.deleteh.as_view(),name = 'hospital_confirm_delete'),
    url(r'doctors_confirm_delete/(?P<pk>\d+)/$',views.deleted.as_view(),name = 'doctors_confirm_delete'),
    url('basic_app_pivot',views.basic_app_pivot,name ='basic_app_pivot'),
    url('data',views.pivot_data,name ='pivot_data'),
    url(r'created/',views.created.as_view(),name ='created'),
    url(r'doctors_list/$',views.doctors_list.as_view(),name = 'doctors_list'),
    url(r'doctors_list/(?P<pk>\d+)/$',views.details.as_view(),name = 'doctors_list'),
    url(r'signup/',views.SignUpView.as_view(),name='signup'),
    url(r'login/',views.loginview.as_view(),name='login'),
    url(r'logout/',views.logoutview.as_view(),name='logout'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls' ,namespace='basic_app')),
    url(r'^$', views.index.as_view(),name = 'index'),

] + static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

basic_app/models.py
from django.db import models
from django.urls import reverse
from django.db.models import F,aggregates
from datetime import datetime
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class doctors(models.Model):
    dname = models.CharField(max_length = 100 , unique = True)
    specality=models.CharField(max_length = 100 , null = True)
    hospitald=models.ForeignKey('basic_app.hospital' ,  on_delete=models.CASCADE , related_name = 'hdoctors' , null=True)
    def __str__(self):
        return self.dname
class hospital(models.Model):
    hname = models.CharField(max_length = 100 , null = True)
    location = models.CharField(max_length = 100 , null = True)
    doctor = models.ForeignKey(doctors ,  on_delete=models.CASCADE , related_name = 'doctord')

    class Meta:
        app_label='basic_app'
        managed = True

    def __str__(self):
        return self.hname

    # def get_absolute_url(self):
    #     return reverse('basic_app:hospital_details' , kwargs = {'pk': self.pk})
GENDER_CHOICES = (
('M','Male'),
('F','Female')
)
cause_choices = (
('A','accident'),('B', 'surgery'),('C','pneumonia'),('D','Infection'),('E','Cardiac Arrhythmiac')
)

class patient(models.Model):
    name = models.CharField(max_length = 100 , null = True)
    Emailid = models.EmailField()
    sex =  models.CharField(max_length = 1 , choices = GENDER_CHOICES )
    date_of_birth = models.DateField(max_length = 8)
    age = models.IntegerField(null = True)
    height = models.FloatField()
    Weight = models.FloatField()
    contact_Number = PhoneNumberField()
    hospitalname = models.ForeignKey(hospital ,  on_delete=models.CASCADE , related_name = 'patients')
    bmi = models.FloatField(null = True)
    doctor_assigned =  models.ForeignKey(doctors ,  on_delete=models.CASCADE , to_field='dname' , related_name = 'doctorh')
    cause = models.CharField(max_length = 1 , choices = cause_choices )
    date_of_admited= models.DateField(max_length = 8)
    date_of_discharge= models.DateField(max_length = 8)
    daysadmited= models.IntegerField(null = True)

    class Meta:
        app_label='basic_app'
        managed = True

    def age_calculate(self):
        age = int((datetime.now().date() - self.date_of_birth).days/365.25)
        return age
    def days_admited(self):
        daysadmited = int((self.date_of_discharge - self.date_of_admited).days)
        return daysadmited

    def calculate_BMI(self):
        bmi = self.Weight/(self.height*self.height)
        return bmi
    def save(self, *args, **kwargs):
        self.bmi=self.calculate_BMI()
        self.age=self.age_calculate()
        self.daysadmited=self.days_admited()
        super().save(*args , **kwargs)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:details' , kwargs = {'pk': self.pk})

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

class SignUpForm(UserCreationForm):
    First_name=forms.CharField(max_length=30 ,required =False,help_text='Optional')
    last_name=forms.CharField(max_length=30 ,required =False,help_text='Optional')
    email =forms.EmailField(max_length=254,help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
        'username',
        'First_name',
        'last_name',
        'email',
        'password1',
        'password2',
        ]
class Authenticate(AuthenticationForm):
    username = forms.CharField(max_length=30,help_text='Enter a valid username')
    password = forms.CharField(widget=forms.PasswordInput,help_text='Enter a valid password')

    class Meta:
        model = User

basic_app/views.py
from django.shortcuts import render
from django.utils.http import is_safe_url
from basic_app.models import hospital , patient
from django.views.generic import TemplateView , ListView, DetailView , View , CreateView ,UpdateView ,DeleteView,FormView , RedirectView
from . import models
from django.urls import reverse_lazy
from django.db.models import F,aggregates
from django.http import JsonResponse
from django.shortcuts import render
from django.core import serializers
from basic_app.forms import SignUpForm,Authenticate
from django.contrib.auth import login,logout,REDIRECT_FIELD_NAME
from django.http import HttpResponseRedirect,HttpResponse

# Create your views here.

def basic_app_pivot(request):
    return render(request,'basic_app/basic_app_pivot.html',{})
def  pivot_data(request):
    dataset=patient.objects.all()
    data=serializers.serialize('json',dataset)
    return JsonResponse(data,safe=False)

class loginview(FormView):
    form_class=Authenticate
    template_name = 'basic_app/login.html'
    success_url = reverse_lazy('basic_app:hospital_list')
    redirect_field_name=REDIRECT_FIELD_NAME
    def dispatch(self,request,*args,**kwargs):
        request.session.set_test_cookie()
        return super(loginview,self).dispatch(request,*args,*kwargs)
    def form_valid(self,form):
        login(self.request,form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return super(loginview,self).form_valid(form)
    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to,allowed_hosts=self.request.get_host()):
            redirect_to=self.success_url
        return redirect_to
class logoutview(RedirectView):
    success_url = reverse_lazy('basic_app:patient_list')
    def get(self,request,*args,**kwargs):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('basic_app:index'))

class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('basic_app:index')
    template_name = 'basic_app/signup.html'

class index(TemplateView):
    template_name = 'basic_app/index.html'

class created(CreateView):
    fields = ('dname','specality','hospitald')
    model = models.doctors
    template_name = 'basic_app/created.html'
    success_url = reverse_lazy('basic_app:doctors_list')

class createp(CreateView):
    fields = ('name','hospitalname','sex','date_of_birth','Emailid','height','Weight','contact_Number','doctor_assigned','date_of_admited','date_of_discharge','cause')
    model=models.patient
    template_name = 'basic_app/createp.html'
    success_url = reverse_lazy('basic_app:patient_list')

class createh(CreateView):
    fields = ('hname','location','doctor')
    model = models.hospital
    template_name = 'basic_app/createh.html'
    success_url = reverse_lazy('basic_app:hospital_list')

class updatep(UpdateView):
    fields = ('name','age','contact_Number','Emailid' , 'height','Weight','doctor_assigned','date_of_admited','date_of_discharge','cause')
    model=models.patient
    success_url = reverse_lazy('basic_app:patient_list')

class updateh(UpdateView):
    fields = ('hname','location','doctor')
    model=models.hospital

class updated(UpdateView):
    fields = ('dname','specality','hospitald')
    model=models.doctors
    success_url = reverse_lazy('basic_app:doctors_list')
class deletep(DeleteView):
    model=models.patient
    success_url = reverse_lazy('basic_app:patient_list')

class deleteh(DeleteView):
    model = models.hospital
    success_url = reverse_lazy('basic_app:hospital_list')

class deleted(DeleteView):
    model = models.doctors
    success_url = reverse_lazy('basic_app:doctors_list')

class details(DetailView):
    model =models.patient
    template_name = 'basic_app/details.html'

class doctors_list(ListView):
    model = models.doctors
    success_url = reverse_lazy('basic_app:patient_list')

class listp(ListView):

    context_object_name = 'list'
    model = models.patient
    success_url = reverse_lazy('basic_app:patient_list')
    # def get_context_data(self,**kwargs):
    #     context=super(listp , self).get_context_data(**kwargs)
    #     return context
class listh(ListView):

    context_object_name = 'hlist'
    model = models.hospital
    success_url = reverse_lazy('basic_app:patient_list')

class hospital_details(DetailView):
    context_object_name = 'hospital_details'
    model = models.hospital
    template_name='basic_app/hospital_details.html'

templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr" >
  <head>
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js">
    </script>
    <link  href="{% static "myblog1.css" %}" rel="stylesheet" >
    <meta charset="utf-8">
    <title></title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">  </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js">

    </script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
  </head>
  <body>
    <div class="page-bg" style="background-image:url({% static 'image5.jpg'%});
      -webkit-filter:blur(5px);
      -moz-filter:blur(5px);
      -o-filter:blur(5px);
      -ms-filter:blur(5px);
      filter: blur(5px);
      position: fixed;
      width: 100%;
      height: 100%;
      top:0;
      right:0;
      z-index:-1;">

    </div>
    {% comment %} <img src="{% static 'image.jpg'%}"> {% endcomment %}
    <nav class="navbar" >
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li class="bg-warning">
          <a class='nav-link' href="{% url 'basic_app:patient_list' %}">patient list</a>
          </li>
          <li class="bg-success">
          <a class = 'nav-link' href="{% url 'basic_app:hospital_list' %}">hospital list</a>
          </li>
          <li class="bg-danger">
          <a class = 'nav-link' href="{% url 'basic_app:createp' %}">create patient</a>
          </li>
          <li class="bg-warning">
          <a class = 'nav-link' href="{% url 'basic_app:createh' %}">create hospital</a>
          </li>
          <li class="bg-success">
          <a class = 'nav-link' href="{% url 'basic_app:created' %}">create doctors</a>
          </li>
          <li class="bg-warning">
          <a class = 'nav-link' href="{% url 'basic_app:doctors_list' %}">doctors list</a>
          {%if user.is_authenticated%}
          </li>
          <li><a class="bg-danger" href="{% url 'basic_app:logout' %}">LOGOUT</a></li>
          {%endif%}
        </ul>
    </div>
      </nav>
      <div class="span" >
      <h3>Belgaum district Health record:</h3>
    </div>
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
  <br><br><br><br><br><br><br><br>
  <footer>
<span class="time" style="color:red;font-size: 15px;padding:5px;filter:blur(0);">{% now "d / m / y  f a" %}</span>
    </footer>
</html>

templates/basic_app/created.html
{% extends 'basic_app/base.html'%}
{%load static%}
{% block body_block %}
<link  href="{% static "myblog1.css" %}" rel="stylesheet" >
<div class="container" style="width:70%;">
  <form class="well form-horizontal" method="POST">
    {% csrf_token %}
    <legend><center><h3><span class="head">New Doctor Entry</span></h3></center></legend>
    <div class="form-group">
      <label class="col-md-3 control-label form-control-label">DOCTOR-NAME</label>
      <div class="col-md-3 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon" ><i class="glyphicon glyphicon-user"></i></span>
          {{form.dname}}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3 control-label form-control-label">specality</label>
      <div class="col-md-3 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon" ><i class="glyphicon glyphicon-star"></i></span>
          {{form.specality}}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3 control-label form-control-label">hospitald</label>
      <div class="col-md-3 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon" ><i class="glyphicon glyphicon-chevron-down"></i></span>
          {{form.hospitald}}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3 control-label form-control-label"></label>
      <div class="col-md-3">
    <button  class ="btn btn-warning" type="submit"> ADD DOCTOR <span class="glyphicon glyphicon-send"></span></button>
    </div>
    </div>
  </form>
  </div>
{% endblock %}

templates/basic_app/createh.html
{% extends 'basic_app/base.html'%}
{%load static%}
{% block body_block %}
<link  href="{% static "myblog1.css" %}" rel="stylesheet" >
<div class="container" style="width:70%;">
  <form class="well form-horizontal" method="POST">
    {% csrf_token %}
    <legend><center><h3><span class="head">New Doctor Entry</span></h3></center></legend>
    <div class="form-group">
      <label class="col-md-3 control-label form-control-label">HOSPITAL-NAME</label>
      <div class="col-md-3 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon" ><i class="glyphicon glyphicon-home"></i></span>
          {{form.hname}}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3 control-label form-control-label">Location</label>
      <div class="col-md-3 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon" ><i class="glyphicon glyphicon-globe"></i></span>
          {{form.location}}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3 control-label form-control-label">Doctor</label>
      <div class="col-md-3 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon" ><i class="glyphicon glyphicon-user"></i></span>
          {{form.doctor}}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-3 control-label form-control-label"></label>
      <div class="col-md-3">
    <button  class ="btn btn-warning" type="submit"> ADD HOSPITAL <span class="glyphicon glyphicon-send"></span></button>
    </div>
    </div>
  </form>
  </div>
{% endblock %}

templates/basic_app/createp.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
{% load static %}
<link  href="{% static "myblog1.css" %}" rel="stylesheet" >
<div class="container" style="width:80%;height70%;">
    <form class="well form-horizontal" method="POST">
       {% csrf_token %}
       <legend><center><h3 ><span class="head">New Patient Registration</span></h3></center></legend>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">FIRST-NAME</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-user"></i></span>
             {{form.name}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">HOSPITAL NAME</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-chevron-down"></i></span>
             {{form.hospitalname}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">SEX</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-chevron-down"></i></span>
             {{form.sex}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">DATE OF BIRTH</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-calendar"></i></span>
             {{form.date_of_birth}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">ADMITED ON</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-calendar"></i></span>
             {{form.date_of_admited}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">DISCHARGE ON</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-calendar"></i></span>
             {{form.date_of_discharge}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">WEIGHT</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-scale"></i></span>
             {{form.Weight}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">HEIGHT</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-scale"></i></span>
             {{form.height}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">EMAIL</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-envelope"></i></span>
             {{form.Emailid}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">DOCTOR ASSIGNED</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-chevron-down"></i></span>
             {{form.doctor_assigned}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">CAUSE</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-chevron-down"></i></span>
             {{form.cause}}
           </div>
         </div>
       </div>
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label">CONTACT NUMBER</label>
         <div class="col-md-3 inputGroupContainer">
           <div class="input-group">
             <span class="input-group-addon" ><i class="glyphicon glyphicon-earphone"></i></span>
             {{form.contact_Number}}
           </div>
         </div>
       </div>


       <!-- {{form.as_p}} -->
       <div class="form-group">
         <label class="col-md-3 control-label form-control-label"></label>
         <div class="col-md-3">
       <button  class ="btn btn-warning" type="submit"> ADD PATIENT <span class="glyphicon glyphicon-send"></span></button>
       </div>
       </div>
    </form>

    </div>
{% endblock%}

templates/basic_app/details.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
    <p>name : {{patient.name}}</p>
    <p>age : {{patient.age}}</p>


{% endblock %}

templates/basic_app/doctors_confirm_delete.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
    <form class=""  method="POST">
      {% csrf_token %}
      <input type="submit" name="" value="delete">
      <a href="{% url 'basic_app:doctors_list' pk=doctors.pk %}"> cancel</a>
    </form>
{% endblock %}

templates/basic_app/doctors_form.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
<div class="container">


    <form class="well form-horizontal"  method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" name="" value="submit" >
    </form>

  </div>
{% endblock %}

templates/basic_app/doctors_list.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
{% load static %}
<link  href="{% static "myblog1.css" %}" rel="stylesheet" >
    <center><h3><span class="head">doctors list</span></h3></center>
    <table class="table table-striped w-auto">
      <thead>
        <th>SN</th>
        <th>doctor name</th>
        <th>specality</th>
        <th>Delete</th>
        <th>Update</th>
      </thead>
      {% for doctors in doctors_list %}
      <tr>
        <td>{{doctors.id}}</td>
        <td><a href="{{ dname.id }}">{{ doctors.dname }}</a></td>
        <td>{{doctors.specality}}</td>
        <td><a class = "btn btn-danger" href="{% url 'basic_app:doctors_confirm_delete' pk=doctors.pk %}">Delete</a></td>
        <td><a class = "btn btn-warning" href="{% url 'basic_app:updated' pk=doctors.pk %}">Update</a></td>
      </tr>
      {% endfor %}
    </table>
{% endblock %}

templates/basic_app/hospital_confirm_delete.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
    <form class=""  method="POST">
      {% csrf_token %}
      <input type="submit" name="" value="delete">
      <a href="{% url 'basic_app:hospital_list' pk=hospital.pk %}"> cancel</a>
    </form>
{% endblock %}

templates/basic_app/hospital_form.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
<div class="container">


    <form class="well form-horizontal"  method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" name="" value="submit" >
    </form>

  </div>
{% endblock %}

templates/basic_app/hospital_list.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
{% load static %}
<link  href="{% static "myblog1.css" %}" rel="stylesheet" >
    <center><h3><span class="head">Hospital record</span></h3></center>
    <table class="table table-striped w-auto">
      <thead>
        <th>SN</th>
        <th>Hospital name</th>
        <th>Location</th>
        <th>Delete</th>
        <th>Update</th>
      </thead>
      {% for hospital in hlist %}
      <tr>
        <td>{{hospital.id}}</td>
        <td><a href="{{ hospital.id }}">{{ hospital.hname }}</a></td>
        <td>{{hospital.location}}</td>
        <td><a class = "btn btn-danger" href="{% url 'basic_app:hospital_confirm_delete' pk=hospital.pk %}">Delete</a></td>
        <td><a class = "btn btn-warning" href="{% url 'basic_app:updateh' pk=hospital.pk %}">Update</a></td>
      </tr>
      {% endfor %}
    </table>

{% endblock %}

templates/basic_app/patient_form.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
<div class="container">


    <form class="well form-horizontal"  method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" name="" value="submit" >
    </form>

  </div>
{% endblock %}

templates/basic_app/patient_list.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
{% load static %}
<link  href="{% static "myblog1.css" %}" rel="stylesheet" >
    <center><h3><span class="head">Patient record</span></h3></center>
    <table class="table table-striped w-auto">
      <thead style="border-style:ridge">
        <th>SN</th>
        <th>Patient name </th>
        <th>Hospital admited</th>``
        <th>sex</th>
        <th>date_of_birth</th>
        <th>date_of_admited</th>
        <!-- <th>date_of_discharge</th> -->
        <th>doctor_assigned</th>
        <th>age</th>
        <th>Email ID</th>
        <!-- <th>Height</th>
        <th>Weight</th> -->
        <th>BMI</th>
        <th>Contact Number</th>
        <th>daysadmited</th>
        <th>Delete</th>
        <th>Update</th>
      </thead>
      {% for patient in list %}
      <tr class="table-info">
        <td>{{patient.id}}</td>
        <td><a href="{{ patient.id }}">{{ patient.name }}</a></td>
        <td>{{ patient.hospitalname}}</td>
        <td>{{ patient.sex }}</td>
        <td>{{ patient.date_of_birth }}</td>
        <td>{{patient.date_of_admited}}</td>
        <!-- <td>{{patient.date_of_discharge}}</td> -->
        <td>{{patient.doctor_assigned.dname}}</td>
        <td>{{ patient.age }}</td>
        <td>{{ patient.Emailid }}</td>
        <!-- <td>{{ patient.height| floatformat:2 }}</td>
        <td >{{ patient.Weight }}</td> -->
        <td >{{patient.bmi| floatformat:2}} </td>
        <td>{{ patient.contact_Number }}</td>
        <td>{{ patient.daysadmited }}</td>
        <td><a class = "btn btn-danger" href="{% url 'basic_app:patient_confirm_delete' pk=patient.pk %}">Delete</a></td>
        <td><a class = "btn btn-warning" href="{% url 'basic_app:updatep' pk=patient.pk %}">Update</a></td>
      </tr>
        {% endfor %}
    </table>

{% endblock %}

'name','hospitalname','sex','date_of_birth','age','Emailid','height','Weight','contact_Number'

templates/basic_app/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h3><strong>SignUp page</strong></h3>
<p>Please fill in the form below</p>

    <form class="" method="POST">
       {% csrf_token %}
       {{form.as_p}}
       <input type="submit" name="" value="Register">
       <br>

    </form>

  </body>
</html>